include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    require_trailing_commas: true
    avoid_print: true
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
