name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  flutter_ci:
    runs-on: ubuntu-latest
    environment: Goms-v3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.38.0
          cache: true
          cache-key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          pub-cache-key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Flutter version check
        run: flutter --version

      - name: Create env asset files
        run: |
          mkdir -p assets/env
          {
            echo "GOMS_API_BASE_URL=${{ secrets.GOMS_API_BASE_URL }}"
            echo "KAKAO_NATIVE_APP_KEY=${{ secrets.KAKAO_NATIVE_APP_KEY }}"
            echo "KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}"
          } > assets/env/dev.env
          cp assets/env/dev.env assets/env/prod.env

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze project source
        run: flutter analyze --no-fatal-warnings --no-fatal-infos

      - name: Run tests
        run: flutter test